services:
  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=America/Sao_Paulo  # Ajuste do fuso horário
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=America/Sao_Paulo  # Ajuste do fuso horário

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka_grafana
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - TZ=America/Sao_Paulo  # Ajuste do fuso horário

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2-data:/var/lib/influxdb2
      - ./influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=rodrigo
      - DOCKER_INFLUXDB_INIT_PASSWORD=123456789
      - DOCKER_INFLUXDB_INIT_ORG=rodr
      - DOCKER_INFLUXDB_INIT_BUCKET=rodr
    depends_on:
      - kafka
      - zookeeper
      - grafana

  producer:
    container_name: produtor
    build:
      context: .
      dockerfile: Dockerfile.produtor
    depends_on:
      - kafka
      - zookeeper
      - influxdb
    environment:
      - TZ=America/Sao_Paulo  # Ajuste do fuso horário


  consumer:
    container_name: consumidor
    build:
      context: .
      dockerfile: Dockerfile.consumidor
    depends_on:
      - kafka
      - zookeeper
      - influxdb
    environment:
      - TZ=America/Sao_Paulo  # Ajuste do fuso horário


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=America/Sao_Paulo  # Ajuste do fuso horário

    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - kafka-ui
      - zookeeper


volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
